# Generated by Django 4.2.11 on 2024-08-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='test',
        ),
    ]
